name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install nmap
        run: sudo apt install nmap && wget https://raw.githubusercontent.com/vulnersCom/nmap-vulners/master/vulners.nse && sudo mv vulners.nse /usr/share/nmap/scripts

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: make test